[package]
name = "rsa-cipher"
version = "0.1.0"
edition = "2024"

[dependencies]
rsa = { version = "0.9.8", features = ["pem"] }
rand = "0.8"
sha2 = "0.10.8"
pkcs8 = { version = "0.10.2", features = ["pem"] }

[dev-dependencies]
hex = "0.4.3"